name: crypto
channels:
  - defaults
dependencies:
  - python=3.7
  - jcopml                                    
  - matplotlib                            
  - numpy                 
  - openpyxl                           
  - pandas                             
  - Pillow                                       
  - plotly                                
  - PyYAML                                 
  - scikit-learn                            
  - seaborn                                     
  - sklearn                            
  - streamlit                      
  - yfinance 